module.exports=function(req,res){
    res.render('runner',{
        component:'tabs',
        externalLinks:[
            '../../../button/assets/picker.css',
            '../../assets/picker.css'
        ]
    });
};