/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('combobox/combobox-tpl',function(){
 return '<div id="ks-combobox-invalid-el{{id}}"      class="{{prefixCls}}combobox-invalid-el">     <div class="{{prefixCls}}combobox-invalid-inner"></div> </div>  {{#if hasTrigger}} <div id="ks-combobox-trigger{{id}}"      class="{{prefixCls}}combobox-trigger">     <div class="{{prefixCls}}combobox-trigger-inner">&#x25BC;</div> </div> {{/if}}  <div class="{{prefixCls}}combobox-input-wrap">      <input id="ks-combobox-input{{id}}"            aria-haspopup="true"            aria-autocomplete="list"            aria-haspopup="true"            role="autocomplete"            aria-expanded="false"      {{#if disabled}}     disabled     {{/if}}      autocomplete="off"     class="{{prefixCls}}combobox-input"      value="{{inputValue}}"     />       <label id="ks-combobox-placeholder{{id}}"            for="ks-combobox-input{{id}}"             style=\'display:{{#if inputValue}}none{{else}}block{{/if}};\'     class="{{prefixCls}}combobox-placeholder">     {{placeholder}}     </label> </div>';
});
