/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('combobox/render-tpl',function(){
 return '<div id="ks-combobox-invalid-el{{id}}"\n     class="{{prefixCls}}combobox-invalid-el">\n    <div class="{{prefixCls}}combobox-invalid-inner"></div>\n</div>\n\n{{#if hasTrigger}}\n<div id="ks-combobox-trigger{{id}}"\n     class="{{prefixCls}}combobox-trigger">\n    <div class="{{prefixCls}}combobox-trigger-inner">&#x25BC;</div>\n</div>\n{{/if}}\n\n<div class="{{prefixCls}}combobox-input-wrap">\n\n    <input id="ks-combobox-input{{id}}"\n           aria-haspopup="true"\n           aria-autocomplete="list"\n           aria-haspopup="true"\n           role="autocomplete"\n           aria-expanded="false"\n\n    {{#if disabled}}\n    disabled\n    {{/if}}\n\n    autocomplete="off"\n    class="{{prefixCls}}combobox-input"\n\n    value="{{inputValue}}"\n    />\n\n\n    <label id="ks-combobox-placeholder{{id}}"\n           for="ks-combobox-input{{id}}"\n        {{#if inputValue}}\n            style=\'display:block;\'\n        {{/if}}\n    class="{{prefixCls}}combobox-placeholder">\n    {{placeholder}}\n    </label>\n</div>';
});
