/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('tree/node-tpl',function(){
 return '<div id="ks-tree-node-row{{id}}"      class="{{prefixCls}}tree-node-row      {{#if selected}}         {{prefixCls}}tree-node-selected      {{/if}}      ">     <div id="ks-tree-expand-icon{{id}}"          class="{{prefixCls}}tree-expand-icon">     </div>     {{#if checkable}}     <div id="ks-tree-node-checked{{id}}"             class="{{prefixCls}}tree-node-check     {{prefixCls}}tree-node-checked{{checkState}}"></div>     {{/if}}     <div id="ks-tree-icon{{id}}"          class="{{prefixCls}}tree-icon">      </div>     <span id=\'ks-tree-node-content{{id}}\'          class="{{prefixCls}}tree-node-content">         {{{content}}}     </span> </div> <div id="ks-tree-children{{id}}"      class="{{prefixCls}}tree-children" {{#if expanded}} {{else}} style="display:none" {{/if}} > </div>';
});
