KISSY.add(KISSY.noop,{
    requires:[
        './delegate',
        './delegate-advanced',
        './event',
        './fire',
        './focus',
        './group',
        './mouse',
        './valuechange'
    ]
});