var editorXX={};
editorXX.addCustomLink("");
editorXX.removeCustomLink("");
editorXX.removeCustomStyle("");
editorXX._onSetMode("");
editorXX.addAttrs({},{});
editorXX._onSetElAttrs();
editorXX._onSetElCls();
editorXX._onSetElStyle();
editorXX._onSetElAttrs();
editorXX._onSetElAttrs();