/** Compiled By kissy-xtemplate */
KISSY.add(function (S, require, exports, module) {
        /*jshint quotmark: false, unused:false, indent:false*/
        return function (scope, S, undefined) {
            var buffer = "",
                config = this.config,
                engine = this,
                moduleWrap, utils = config.utils;
            if (typeof module !== "undefined" && module.kissy) {
                moduleWrap = module;
            }
            var runBlockCommandUtil = utils.runBlockCommand,
                getExpressionUtil = utils.getExpression,
                getPropertyOrRunCommandUtil = utils.getPropertyOrRunCommand;
            buffer += '<div class="';
            var config1 = {};
            var params2 = [];
            params2.push('header');
            config1.params = params2;
            var id0 = getPropertyOrRunCommandUtil(engine, scope, config1, "getBaseCssClasses", 0, 1, true, undefined);
            buffer += id0;
            buffer += '">\n    <a id="ks-date-picker-previous-year-btn-';
            var id3 = getPropertyOrRunCommandUtil(engine, scope, {}, "id", 0, 2, undefined, false);
            buffer += getExpressionUtil(id3, true);
            buffer += '"\n       class="';
            var config5 = {};
            var params6 = [];
            params6.push('prev-year-btn');
            config5.params = params6;
            var id4 = getPropertyOrRunCommandUtil(engine, scope, config5, "getBaseCssClasses", 0, 3, true, undefined);
            buffer += id4;
            buffer += '"\n       href="#"\n       tabindex="-1"\n       role="button"\n       title="';
            var id7 = getPropertyOrRunCommandUtil(engine, scope, {}, "previousYearLabel", 0, 7, undefined, false);
            buffer += getExpressionUtil(id7, true);
            buffer += '"\n       hidefocus="on">\n    </a>\n    <a id="ks-date-picker-previous-month-btn-';
            var id8 = getPropertyOrRunCommandUtil(engine, scope, {}, "id", 0, 10, undefined, false);
            buffer += getExpressionUtil(id8, true);
            buffer += '"\n       class="';
            var config10 = {};
            var params11 = [];
            params11.push('prev-month-btn');
            config10.params = params11;
            var id9 = getPropertyOrRunCommandUtil(engine, scope, config10, "getBaseCssClasses", 0, 11, true, undefined);
            buffer += id9;
            buffer += '"\n       href="#"\n       tabindex="-1"\n       role="button"\n       title="';
            var id12 = getPropertyOrRunCommandUtil(engine, scope, {}, "previousMonthLabel", 0, 15, undefined, false);
            buffer += getExpressionUtil(id12, true);
            buffer += '"\n       hidefocus="on">\n    </a>\n    <a class="';
            var config14 = {};
            var params15 = [];
            params15.push('month-select');
            config14.params = params15;
            var id13 = getPropertyOrRunCommandUtil(engine, scope, config14, "getBaseCssClasses", 0, 18, true, undefined);
            buffer += id13;
            buffer += '"\n       role="button"\n       href="#"\n       tabindex="-1"\n       hidefocus="on"\n       title="';
            var id16 = getPropertyOrRunCommandUtil(engine, scope, {}, "monthSelectLabel", 0, 23, undefined, false);
            buffer += getExpressionUtil(id16, true);
            buffer += '"\n       id="ks-date-picker-month-select-';
            var id17 = getPropertyOrRunCommandUtil(engine, scope, {}, "id", 0, 24, undefined, false);
            buffer += getExpressionUtil(id17, true);
            buffer += '">\n        <span id="ks-date-picker-month-select-content-';
            var id18 = getPropertyOrRunCommandUtil(engine, scope, {}, "id", 0, 25, undefined, false);
            buffer += getExpressionUtil(id18, true);
            buffer += '">';
            var id19 = getPropertyOrRunCommandUtil(engine, scope, {}, "monthYearLabel", 0, 25, undefined, false);
            buffer += getExpressionUtil(id19, true);
            buffer += '</span>\n        <span class="';
            var config21 = {};
            var params22 = [];
            params22.push('month-select-arrow');
            config21.params = params22;
            var id20 = getPropertyOrRunCommandUtil(engine, scope, config21, "getBaseCssClasses", 0, 26, true, undefined);
            buffer += id20;
            buffer += '">x</span>\n    </a>\n    <a id="ks-date-picker-next-month-btn-';
            var id23 = getPropertyOrRunCommandUtil(engine, scope, {}, "id", 0, 28, undefined, false);
            buffer += getExpressionUtil(id23, true);
            buffer += '"\n       class="';
            var config25 = {};
            var params26 = [];
            params26.push('next-month-btn');
            config25.params = params26;
            var id24 = getPropertyOrRunCommandUtil(engine, scope, config25, "getBaseCssClasses", 0, 29, true, undefined);
            buffer += id24;
            buffer += '"\n       href="#"\n       tabindex="-1"\n       role="button"\n       title="';
            var id27 = getPropertyOrRunCommandUtil(engine, scope, {}, "nextMonthLabel", 0, 33, undefined, false);
            buffer += getExpressionUtil(id27, true);
            buffer += '"\n       hidefocus="on">\n    </a>\n    <a id="ks-date-picker-next-year-btn-';
            var id28 = getPropertyOrRunCommandUtil(engine, scope, {}, "id", 0, 36, undefined, false);
            buffer += getExpressionUtil(id28, true);
            buffer += '"\n       class="';
            var config30 = {};
            var params31 = [];
            params31.push('next-year-btn');
            config30.params = params31;
            var id29 = getPropertyOrRunCommandUtil(engine, scope, config30, "getBaseCssClasses", 0, 37, true, undefined);
            buffer += id29;
            buffer += '"\n       href="#"\n       tabindex="-1"\n       role="button"\n       title="';
            var id32 = getPropertyOrRunCommandUtil(engine, scope, {}, "nextYearLabel", 0, 41, undefined, false);
            buffer += getExpressionUtil(id32, true);
            buffer += '"\n       hidefocus="on">\n    </a>\n</div>\n<div class="';
            var config34 = {};
            var params35 = [];
            params35.push('body');
            config34.params = params35;
            var id33 = getPropertyOrRunCommandUtil(engine, scope, config34, "getBaseCssClasses", 0, 45, true, undefined);
            buffer += id33;
            buffer += '">\n    <table class="';
            var config37 = {};
            var params38 = [];
            params38.push('table');
            config37.params = params38;
            var id36 = getPropertyOrRunCommandUtil(engine, scope, config37, "getBaseCssClasses", 0, 46, true, undefined);
            buffer += id36;
            buffer += '" cellspacing="0" role="grid">\n        <thead>\n        <tr role="row">\n            ';
            var config39 = {};
            var params40 = [];
            var id41 = getPropertyOrRunCommandUtil(engine, scope, {}, "showWeekNumber", 0, 49, undefined, true);
            params40.push(id41);
            config39.params = params40;
            config39.fn = function (scope) {
                var buffer = "";
                buffer += '\n            <th role="columnheader" class="';
                var config43 = {};
                var params44 = [];
                params44.push('column-header');
                config43.params = params44;
                var id42 = getPropertyOrRunCommandUtil(engine, scope, config43, "getBaseCssClasses", 0, 50, true, undefined);
                buffer += id42;
                buffer += ' ';
                var config46 = {};
                var params47 = [];
                params47.push('week-number-header');
                config46.params = params47;
                var id45 = getPropertyOrRunCommandUtil(engine, scope, config46, "getBaseCssClasses", 0, 50, true, undefined);
                buffer += id45;
                buffer += '">\n                <span class="';
                var config49 = {};
                var params50 = [];
                params50.push('column-header-inner');
                config49.params = params50;
                var id48 = getPropertyOrRunCommandUtil(engine, scope, config49, "getBaseCssClasses", 0, 51, true, undefined);
                buffer += id48;
                buffer += '">x</span>\n            </th>\n            ';
                return buffer;
            };
            buffer += runBlockCommandUtil(engine, scope, config39, "if", 49);
            buffer += '\n            ';
            var config51 = {};
            var params52 = [];
            var id53 = getPropertyOrRunCommandUtil(engine, scope, {}, "weekdays", 0, 54, undefined, true);
            params52.push(id53);
            config51.params = params52;
            config51.fn = function (scope) {
                var buffer = "";
                buffer += '\n            <th role="columnheader" title="';
                var id54 = getPropertyOrRunCommandUtil(engine, scope, {}, ".", 0, 55, undefined, false);
                buffer += getExpressionUtil(id54, true);
                buffer += '" class="';
                var config56 = {};
                var params57 = [];
                params57.push('column-header');
                config56.params = params57;
                var id55 = getPropertyOrRunCommandUtil(engine, scope, config56, "getBaseCssClasses", 0, 55, true, undefined);
                buffer += id55;
                buffer += '">\n                <span class="';
                var config59 = {};
                var params60 = [];
                params60.push('column-header-inner');
                config59.params = params60;
                var id58 = getPropertyOrRunCommandUtil(engine, scope, config59, "getBaseCssClasses", 0, 56, true, undefined);
                buffer += id58;
                buffer += '">\n                    ';
                var id62 = getPropertyOrRunCommandUtil(engine, scope, {}, "xindex", 0, 57, undefined, true);
                var id61 = getPropertyOrRunCommandUtil(engine, scope, {}, "veryShortWeekdays." + id62 + "", 0, 57, undefined, false);
                buffer += getExpressionUtil(id61, true);
                buffer += '\n                </span>\n            </th>\n            ';
                return buffer;
            };
            buffer += runBlockCommandUtil(engine, scope, config51, "each", 54);
            buffer += '\n        </tr>\n        </thead>\n        <tbody id="ks-date-picker-tbody-';
            var id63 = getPropertyOrRunCommandUtil(engine, scope, {}, "id", 0, 63, undefined, false);
            buffer += getExpressionUtil(id63, true);
            buffer += '">\n        ';
            var id64 = getPropertyOrRunCommandUtil(engine, scope, {}, "renderDates", 0, 64, undefined, false);
            buffer += getExpressionUtil(id64, false);
            buffer += '\n        </tbody>\n    </table>\n</div>\n';
            var config65 = {};
            var params66 = [];
            var id67 = getPropertyOrRunCommandUtil(engine, scope, {}, "showToday", 0, 68, undefined, true);
            var id68 = getPropertyOrRunCommandUtil(engine, scope, {}, "showClear", 0, 68, undefined, true);
            params66.push(id67 || id68);
            config65.params = params66;
            config65.fn = function (scope) {
                var buffer = "";
                buffer += '\n<div class="';
                var config70 = {};
                var params71 = [];
                params71.push('footer');
                config70.params = params71;
                var id69 = getPropertyOrRunCommandUtil(engine, scope, config70, "getBaseCssClasses", 0, 69, true, undefined);
                buffer += id69;
                buffer += '">\n    <a class="';
                var config73 = {};
                var params74 = [];
                params74.push('today-btn');
                config73.params = params74;
                var id72 = getPropertyOrRunCommandUtil(engine, scope, config73, "getBaseCssClasses", 0, 70, true, undefined);
                buffer += id72;
                buffer += '"\n       role="button"\n       hidefocus="on"\n       tabindex="-1"\n       href="#"\n       id="ks-date-picker-today-btn-';
                var id75 = getPropertyOrRunCommandUtil(engine, scope, {}, "id", 0, 75, undefined, false);
                buffer += getExpressionUtil(id75, true);
                buffer += '"\n       title="';
                var id76 = getPropertyOrRunCommandUtil(engine, scope, {}, "todayTimeLabel", 0, 76, undefined, false);
                buffer += getExpressionUtil(id76, true);
                buffer += '">';
                var id77 = getPropertyOrRunCommandUtil(engine, scope, {}, "todayLabel", 0, 76, undefined, false);
                buffer += getExpressionUtil(id77, true);
                buffer += '</a>\n    <a class="';
                var config79 = {};
                var params80 = [];
                params80.push('clear-btn');
                config79.params = params80;
                var id78 = getPropertyOrRunCommandUtil(engine, scope, config79, "getBaseCssClasses", 0, 77, true, undefined);
                buffer += id78;
                buffer += '"\n       role="button"\n       hidefocus="on"\n       tabindex="-1"\n       href="#"\n       id="ks-date-picker-clear-btn-';
                var id81 = getPropertyOrRunCommandUtil(engine, scope, {}, "id", 0, 82, undefined, false);
                buffer += getExpressionUtil(id81, true);
                buffer += '">';
                var id82 = getPropertyOrRunCommandUtil(engine, scope, {}, "clearLabel", 0, 82, undefined, false);
                buffer += getExpressionUtil(id82, true);
                buffer += '</a>\n</div>\n';
                return buffer;
            };
            buffer += runBlockCommandUtil(engine, scope, config65, "if", 68);
            return buffer;
        };
});