
(function(config,Features,UA){
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/back-color': {requires: ['editor','editor/plugin/color/btn']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/back-color/cmd': {requires: ['editor/plugin/color/cmd']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/bold': {requires: ['editor','editor/plugin/font/ui']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/bold/cmd': {requires: ['editor','editor/plugin/font/cmd']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/bubble': {requires: ['overlay','editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/button': {requires: ['editor','button']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/checkbox-source-area': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/code': {requires: ['editor','editor/plugin/dialog-loader']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/code/dialog': {requires: ['editor','editor/plugin/dialog','menubutton']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/color/btn': {requires: ['editor','editor/plugin/button','editor/plugin/overlay','editor/plugin/dialog-loader']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/color/cmd': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/color/dialog': {requires: ['editor','editor/plugin/dialog']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/contextmenu': {requires: ['editor','menu','editor/plugin/focus-fix']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/dent-cmd': {requires: ['editor','editor/plugin/list-utils']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/dialog-loader': {requires: ['overlay','editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/dialog': {requires: ['editor','overlay','editor/plugin/focus-fix','dd/plugin/constrain','component/plugin/drag']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/draft': {requires: ['editor','editor/plugin/local-storage','overlay','editor/plugin/menubutton']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/drag-upload': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/element-path': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/fake-objects': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/flash-bridge': {requires: ['swf','editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/flash-common/base-class': {requires: ['editor','editor/plugin/contextmenu','editor/plugin/bubble','editor/plugin/dialog-loader','editor/plugin/flash-common/utils']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/flash-common/utils': {requires: ['swf']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/flash': {requires: ['editor','editor/plugin/flash-common/base-class','editor/plugin/flash-common/utils','editor/plugin/fake-objects']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/flash/dialog': {requires: ['editor','editor/plugin/flash-common/utils','editor/plugin/dialog','editor/plugin/menubutton']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/focus-fix': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/font-family': {requires: ['editor','editor/plugin/font/ui']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/font-family/cmd': {requires: ['editor','editor/plugin/font/cmd']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/font-size': {requires: ['editor','editor/plugin/font/ui']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/font-size/cmd': {requires: ['editor','editor/plugin/font/cmd']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/font/cmd': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/font/ui': {requires: ['editor','editor/plugin/button','editor/plugin/menubutton']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/fore-color': {requires: ['editor','editor/plugin/color/btn']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/fore-color/cmd': {requires: ['editor/plugin/color/cmd']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/heading': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/heading/cmd': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/image': {requires: ['editor','editor/plugin/button','editor/plugin/bubble','editor/plugin/contextmenu','editor/plugin/dialog-loader']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/image/dialog': {requires: ['io','editor','editor/plugin/dialog','tabs','editor/plugin/menubutton']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/indent': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/indent/cmd': {requires: ['editor','editor/plugin/dent-cmd']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/italic': {requires: ['editor','editor/plugin/font/ui']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/italic/cmd': {requires: ['editor','editor/plugin/font/cmd']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/justify-center': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/justify-center/cmd': {requires: ['editor/plugin/justify-cmd']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/justify-cmd': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/justify-left': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/justify-left/cmd': {requires: ['editor/plugin/justify-cmd']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/justify-right': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/justify-right/cmd': {requires: ['editor/plugin/justify-cmd']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/link': {requires: ['editor','editor/plugin/bubble','editor/plugin/dialog-loader','editor/plugin/button']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/link/dialog': {requires: ['editor','editor/plugin/dialog','editor/plugin/link/utils']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/link/utils': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/list-utils': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/list-utils/btn': {requires: ['editor','editor/plugin/button','editor/plugin/menubutton']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/list-utils/cmd': {requires: ['editor','editor/plugin/list-utils']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/local-storage': {requires: ['editor','overlay','editor/plugin/flash-bridge']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/maximize': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/maximize/cmd': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/menubutton': {requires: ['editor','menubutton']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/multiple-upload': {requires: ['editor','editor/plugin/dialog-loader']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/multiple-upload/dialog': {requires: ['editor','component/plugin/drag','editor/plugin/progressbar','editor/plugin/dialog','editor/plugin/flash-bridge','editor/plugin/local-storage','swf']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/ordered-list': {requires: ['editor','editor/plugin/list-utils/btn']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/ordered-list/cmd': {requires: ['editor','editor/plugin/list-utils/cmd']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/outdent': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/outdent/cmd': {requires: ['editor','editor/plugin/dent-cmd']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/overlay': {requires: ['editor','overlay','editor/plugin/focus-fix']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/page-break': {requires: ['editor','editor/plugin/fake-objects']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/remove-format': {requires: ['editor','editor/plugin/button']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/remove-format/cmd': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/resize': {requires: ['editor','dd/base']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/separator': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/smiley': {requires: ['editor','editor/plugin/overlay']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/source-area': {requires: ['editor','editor/plugin/button']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/strike-through': {requires: ['editor','editor/plugin/font/ui']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/strike-through/cmd': {requires: ['editor','editor/plugin/font/cmd']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/table': {requires: ['editor','editor/plugin/dialog-loader','editor/plugin/contextmenu']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/table/dialog': {requires: ['editor','editor/plugin/dialog','editor/plugin/menubutton']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/underline': {requires: ['editor','editor/plugin/font/ui']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/underline/cmd': {requires: ['editor','editor/plugin/font/cmd']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/undo': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/undo/btn': {requires: ['editor','editor/plugin/button']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/undo/cmd': {requires: ['editor']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/unordered-list': {requires: ['editor','editor/plugin/list-utils/btn']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/unordered-list/cmd': {requires: ['editor','editor/plugin/list-utils/cmd']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/video': {requires: ['editor','editor/plugin/flash-common/utils','editor/plugin/flash-common/base-class','editor/plugin/fake-objects']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/video/dialog': {requires: ['editor','editor/plugin/flash/dialog','editor/plugin/menubutton']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/word-filter': {requires: ['htmlparser']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/xiami-music': {requires: ['editor','editor/plugin/flash-common/base-class','editor/plugin/flash-common/utils','editor/plugin/fake-objects']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/xiami-music/dialog': {requires: ['editor','editor/plugin/flash/dialog','editor/plugin/menubutton']}
});

                })(function(c){
                KISSY.config('modules', c);
                },KISSY.Features,KISSY.UA);
            