/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('component/extension/content-render/content-tpl',
'<div id="ks-content-{{id}}"\n           class="{{getBaseCssClasses \'content\'}}">{{{content}}}</div>');
