/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('overlay/close-tpl',function(){
 return '{{#if closable}}\n<a href="javascript:void(\'close\')"\n   id="ks-ext-close{{id}}"\n   class="{{prefixCls}}ext-close"\n   role=\'button\'>\n    <span class="{{prefixCls}}ext-close-x">close</span>\n</a>\n{{/if}}';
});
