/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('overlay/overlay-tpl',function(){
 return '<div id="ks-contentbox{{id}}"      class="{{prefixCls}}contentbox {{prefixCls}}overlay-contentbox">     {{{content}}} </div>';
});
