KISSY.add("note/mods/NoteView",function(e,i,c,k){function d(){d.superclass.constructor.apply(this,arguments);this.get("note").on("*Change",this.render,this);this.get("note").on("destroy",this.destroy,this)}var j=k(i.all("#noteTpl").html());e.extend(d,c.View,{render:function(){this.get("el").addClass("note").attr("id",this.get("note").getId());this.get("el").html(j.render({note:this.get("note").toJSON()}));return this},destroy:function(){this.get("el").remove()}});return d},{requires:["node","mvc",
"template"]});
KISSY.add("note/mods/NotesView",function(e,i,c,k,d){function j(){j.superclass.constructor.apply(this,arguments);var a=this,h,f,l=a.get("el");a.searchInput=l.one(".searchInput");f=a.dataList=l.one(".dataList");h=a.statistic=l.one(".statistic");var m=a.get("notes");m.on("*Change",function(n){n.target!=a&&h.html(n.target.get("title"))});m.on("add remove",function(n){h.html(n.model.get("title"))});m.on("add",function(n){f.append((new d({note:n.model})).render().get("el"))});m.on("afterModelsChange",function(){f.html(g.render({list:m.toJSON()}));
f.all(".note").each(function(n,o){new d({note:m.at(o),el:n})})})}var b=i.all,g=k(b("#listTpl").html());e.extend(j,c.View,{newNote:function(){c.Router.navigate("/new/")},refreshNote:function(){this.get("notes").load()},editNote:function(a){c.Router.navigate("/edit/"+b(a.currentTarget).parent("div").attr("id"))},deleteNode:function(a){this.get("notes").getById(b(a.currentTarget).parent("div").attr("id")).destroy({"delete":1})},search:function(){e.trim(this.searchInput.val())&&c.Router.navigate("/search/?q="+
encodeURIComponent(this.searchInput.val()))},keyup:function(a){if(a.keyCode==13){a.halt();this.searchInput[0].focus();this.search()}}},{ATTRS:{el:{value:"#list"},events:{value:{".edit":{click:"editNote"},".newNote":{click:"newNote"},".delete":{click:"deleteNode"},".refreshNote":{click:"refreshNote"},".searchNote":{click:"search"},".searchInput":{keyup:"keyup"}}}}});return j},{requires:["node","mvc","template","./NoteView"]});
KISSY.add("note/mods/EditView",function(e,i,c,k){function d(){d.superclass.constructor.apply(this,arguments)}var j=k(i.all("#detailTpl").html());e.extend(d,c.View,{submit:function(){var b=this.get("note"),g=this.get("el");b.set({title:g.one(".title").val(),content:g.one(".content").val()});this.fire("submit",{note:b})},render:function(){this.get("el").html(j.render({note:this.get("note").toJSON()}));return this}},{ATTRS:{el:{value:"#edit"},events:{value:{".submit":{click:"submit"}}}}});return d},
{requires:["node","mvc","template"]});KISSY.add("note/mods/NoteModel",function(e,i){function c(){c.superclass.constructor.apply(this,arguments)}e.extend(c,i.Model);return c},{requires:["mvc"]});KISSY.add("note/mods/NotesCollection",function(e,i,c){function k(){k.superclass.constructor.apply(this,arguments)}e.extend(k,i.Collection,{ATTRS:{Model:{value:c}}});return k},{requires:["mvc","./NoteModel"]});
KISSY.add("note/mods/SearchView",function(e,i,c,k){function d(){var b=this;d.superclass.constructor.apply(this,arguments);this.searchInput=this.get("el").one(".searchInput");this.searchList=this.get("el").one(".searchList");this.get("notes").on("afterModelsChange",function(){b.searchList.html(j.render({list:b.get("notes").toJSON()}))})}i=i.all;var j=k(i("#searchTpl").html());e.extend(d,c.View,{search:function(){e.trim(this.searchInput.val())&&c.Router.navigate("/search/?q="+encodeURIComponent(this.searchInput.val()))},
keyup:function(b){if(b.keyCode==13){b.halt();this.searchInput[0].focus();this.search()}},back:function(){this.searchInput.val("");c.Router.navigate("/")}},{ATTRS:{el:{value:"#search"},events:{value:{".searchBtn":{click:"search"},".backBtn":{click:"back"},".searchInput":{keyup:"keyup"}}}}});return d},{requires:["node","mvc","template"]});
KISSY.add("note/mods/router",function(e,i,c,k,d,j,b,g){function a(){a.superclass.constructor.apply(this,arguments);this.notesView=new k({notes:new j});this.editView=new d;this.notesView.get("notes").load();this.editView.on("submit",this._onEditSubmit,this);this.searchView=new g({notes:new j})}var h=e.Node.all;e.extend(a,c.Router,{_onEditSubmit:function(f){f=f.note;var l=this.notesView.get("notes");if(f.isNew())l.create(f,{success:function(){c.Router.navigate("")}});else{l=l.getById(f.getId());l.set(f.toJSON());
l.save({success:function(){c.Router.navigate("")}})}},index:function(){h(".page").hide();this.notesView.get("el").show()},editNote:function(f){var l=new b({id:f.id}),m=this.editView;l.load({success:function(){h(".page").hide();m.set("note",l);m.render();m.get("el").show()}})},newNote:function(){var f=this.editView;h(".page").hide();f.set("note",new b);f.render().get("el").show()},search:function(f,l){var m=decodeURIComponent(l.q),n=this;n.searchView.searchInput.val(m);n.searchView.get("notes").load({data:{q:m},
success:function(){h(".page").hide();n.searchView.get("el").show()}})}},{ATTRS:{routes:{value:{"/":"index","":"index","/edit/:id":"editNote","/new/":"newNote","/search/":"search"}}}});return a},{requires:["node","mvc","./NotesView","./EditView","./NotesCollection","./NoteModel","./SearchView"]});
KISSY.add("note/mods/sync",function(e,i){function c(d,j){for(var b=0;b<d.length;b++)if(d[b].id==j)return b;return-1}var k;return i.sync=function(d,j,b){b=b||{};e.log(j);setTimeout(function(){var g,a=k||(window.localStorage?window.localStorage.getItem("KISSY_Note")||[]:[]);if(e.isString(a))a=JSON.parse(a);var h,f;switch(j){case "read":var l;if(b.data&&(l=b.data.q)){h=[];for(g in a)a[g].title.indexOf(l)>-1&&h.push(a[g])}else if(d instanceof i.Model)(h=a[c(a,d.get("id"))])||(f="not found");else{h=[];
for(g in a)h.push(a[g])}break;case "create":h=d.toJSON();h.id=e.guid("note");h.time=(new Date).toLocaleTimeString();a.push(h);break;case "delete":g=d.get("id");g=c(a,g);g>-1&&a.splice(g,1);break;case "update":g=d.get("id");g=c(a,g);if(g>-1)a[g]=d.toJSON()}j!="read"&&window.localStorage&&window.localStorage.setItem("KISSY_Note",e.JSON.stringify(a));k=a;if(f)b.error&&b.error(null,f);else b.success&&b.success(h);b.complete&&b.complete(h,f)},500)}},{requires:["mvc"]});
KISSY.add("note/main2",function(e,i,c,k,d){new c;d.Router.start({triggerRoute:1,nativeHistory:1,urlRoot:location.hostname=="localhost"?"/kissy_git/kissy/src/mvc/demo/note_html5":"/kissy/src/mvc/demo/note_html5",success:function(){i.all("#loading").hide()}})},{requires:["node","./mods/router","./mods/sync","mvc"]});
