KISSY.add("note/mods/NoteView",function(g,f,e,j){function c(){c.superclass.constructor.apply(this,arguments);this.get("note").on("*Change",this.render,this);this.get("note").on("destroy",this.destroy,this)}var h=j(f.all("#noteTpl").html());g.extend(c,e.View,{render:function(){this.get("el").addClass("note").attr("id",this.get("note").getId());this.get("el").html(h.render({note:this.get("note").toJSON()}));return this},destroy:function(){this.get("el").remove()}});return c},{requires:["node","mvc",
"template"]});
KISSY.add("note/mods/NotesView",function(g,f,e,j,c){function h(){h.superclass.constructor.apply(this,arguments);var a=this,i,k,n=a.get("el");k=a.dataList=n.one(".dataList");i=a.statistic=n.one(".statistic");var m=a.get("notes");m.on("*Change",function(l){l.target!=a&&i.html(l.target.get("title"))});m.on("add remove",function(l){i.html(l.model.get("title"))});m.on("add",function(l){k.append((new c({note:l.model})).render().get("el"))});m.on("afterModelsChange",function(){k.html(b.render({list:m.toJSON()}));k.all(".note").each(function(l,
o){new c({note:m.at(o),el:l})})})}var d=f.all,b=j(d("#listTpl").html());g.extend(h,e.View,{newNote:function(){e.Router.navigate("/new/")},refreshNote:function(){this.get("notes").load()},editNote:function(a){e.Router.navigate("/edit/"+d(a.currentTarget).parent("div").attr("id"))},deleteNode:function(a){this.get("notes").getById(d(a.currentTarget).parent("div").attr("id")).destroy({"delete":1})}},{ATTRS:{el:{value:"#list"},events:{value:{".edit":{click:"editNote"},".newNote":{click:"newNote"},".delete":{click:"deleteNode"},
".refreshNote":{click:"refreshNote"}}}}});return h},{requires:["node","mvc","template","./NoteView"]});
KISSY.add("note/mods/EditView",function(g,f,e,j){function c(){c.superclass.constructor.apply(this,arguments)}var h=j(f.all("#detailTpl").html());g.extend(c,e.View,{submit:function(){var d=this.get("note"),b=this.get("el");d.set({title:b.one(".title").val(),content:b.one(".content").val()});this.fire("submit",{note:d})},render:function(){this.get("el").html(h.render({note:this.get("note").toJSON()}));return this}},{ATTRS:{el:{value:"#edit"},events:{value:{".submit":{click:"submit"}}}}});return c},
{requires:["node","mvc","template"]});KISSY.add("note/mods/NoteModel",function(g,f){function e(){e.superclass.constructor.apply(this,arguments)}g.extend(e,f.Model);return e},{requires:["mvc"]});KISSY.add("note/mods/NotesCollection",function(g,f,e){function j(){j.superclass.constructor.apply(this,arguments)}g.extend(j,f.Collection,{ATTRS:{Model:{value:e}}});return j},{requires:["mvc","./NoteModel"]});
KISSY.add("note/mods/router",function(g,f,e,j,c,h){function d(){d.superclass.constructor.apply(this,arguments);this.notesView=new e({notes:new c,router:this});this.editView=new j;this.notesView.get("notes").load();this.editView.on("submit",this._onEditSubmit,this)}g.extend(d,f.Router,{_onEditSubmit:function(b){b=b.note;var a=this.notesView.get("notes");if(b.isNew())a.create(b,{success:function(){f.Router.navigate("")}});else{a=a.getById(b.getId());a.set(b.toJSON());a.save({success:function(){f.Router.navigate("")}})}},
index:function(){this.editView.get("el").hide();this.notesView.get("el").show()},editNote:function(b){var a=this,i=new h({id:b.id}),k=a.editView;i.load({success:function(){a.notesView.get("el").hide();k.set("note",i);k.render();k.get("el").show()}})},newNote:function(){var b=this.editView;this.notesView.get("el").hide();b.set("note",new h);b.render().get("el").show()}},{ATTRS:{routes:{value:{"/":"index","":"index","/edit/:id":"editNote","/new/":"newNote"}}}});return d},{requires:["mvc","./NotesView",
"./EditView","./NotesCollection","./NoteModel"]});
KISSY.add("note/mods/sync",function(g,f){function e(c,h){for(var d=0;d<c.length;d++)if(c[d].id==h)return d;return-1}var j;return f.sync=function(c,h,d){g.log(h);setTimeout(function(){var b,a=j||(window.localStorage?window.localStorage.getItem("KISSY_Note")||[]:[]);if(g.isString(a))a=JSON.parse(a);var i,k;switch(h){case "read":if(c instanceof f.Model)(i=a[e(a,c.get("id"))])||(k="not found");else{i=[];for(b in a)i.push(a[b])}break;case "create":i=c.toJSON();i.id=g.guid("note");i.time=(new Date).toLocaleTimeString();
a.push(i);break;case "delete":b=c.get("id");b=e(a,b);b>-1&&a.splice(b,1);break;case "update":b=c.get("id");b=e(a,b);if(b>-1)a[b]=c.toJSON()}h!="read"&&window.localStorage&&window.localStorage.setItem("KISSY_Note",g.JSON.stringify(a));j=a;if(k)d.error&&d.error(null,k);else d.success&&d.success(i);d.complete&&d.complete(i,k)},500)}},{requires:["mvc"]});
KISSY.add("note/main",function(g,f,e,j,c){new e;c.Router.start({triggerRoute:1,nativeHistory:1,urlRoot:location.hostname=="localhost"?"/kissy_git/kissy/src/mvc/demo/note_html5":"/kissy/src/mvc/demo/note_html5",success:function(){f.all("#loading").hide()}})},{requires:["node","./mods/router","./mods/sync","mvc"]});
