/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('component/base/box-tpl',function(){
 return '<div id="ks-component{{id}}" \n class="{{getCssClassWithState ""}}\n\n{{#if visible}} \n{{getCssClassWithState "shown"}}  \n{{else}} \n{{getCssClassWithState "hidden"}}  \n{{/if}} \n\n{{#if elCls}} \n{{#each elCls}} \n {{.}}  \n{{/each}} \n{{/if}}\n"\n\n{{#if elAttrs}} \n{{#each elAttrs}} \n {{xkey}}="{{.}}"  \n{{/each}}  \n{{/if}} \n\nstyle=" \n{{#if elStyle}}\n{{#each elStyle}} \n {{xkey}}:{{.}};  \n{{/each}} \n{{/if}}  \n\n{{#if width}} \nwidth:{{width}}; \n{{/if}} \n\n{{#if height}} \nheight:{{height}}; \n{{/if}} \n">';
});
