/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('component/base/box-tpl',function(){
 return '<div id="ks-component{{id}}" class="{{getCssClassWithState ""}} {{#each elCls}} {{.}} {{/each}} " {{#each elAttrs}} {{xkey}}="{{.}}" {{/each}} style=" {{#each elStyle}} {{xkey}}:{{.}}; {{/each}} ">';
});
