/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/editor-multiple-uploader/dialog': {requires: ['node','editor','component/plugin/drag','editor/plugin/dialog','gallery/uploader/1.4/','gallery/uploader/1.4/themes/editorMultipleUploader/','gallery/uploader/1.4/plugins/auth/auth','gallery/uploader/1.4/plugins/proBars/proBars','gallery/uploader/1.4/themes/editorMultipleUploader/style.css']}
});
