/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('date/picker/decade-panel/decades-tpl',
'{{#each decades}}\n<tr role="row">\n    {{#each decades[xindex]}}\n    <td role="gridcell"\n        class="{{getBaseCssClasses \'cell\'}}\n        {{#if startDecade<=year&&year<=endDecade}}\n         {{getBaseCssClasses \'selected-cell\'}}\n        {{/if}}\n        {{#if startDecade<startYear}}\n         {{getBaseCssClasses \'last-century-cell\'}}\n        {{/if}}\n        {{#if endDecade>endYear}}\n         {{getBaseCssClasses \'next-century-cell\'}}\n        {{/if}}\n        ">\n        <a hidefocus="on"\n           href="#"\n           class="{{getBaseCssClasses \'decade\'}}">\n            {{startDecade}}-{{endDecade}}\n        </a>\n    </td>\n    {{/each}}\n</tr>\n{{/each}}');
