/*
  Generated by kissy-xtemplate.*/
KISSY.add('menubutton/menubutton-xtpl', function () {
    return function (scopes, S, undefined) {
        var buffer = "",
            config = this.config,
            engine = this,
            utils = config.utils;
        var runBlockCommandUtil = utils["runBlockCommand"],
            getExpressionUtil = utils["getExpression"],
            getPropertyOrRunCommandUtil = utils["getPropertyOrRunCommand"];
        buffer += '';
        var config1 = {};
        var params2 = [];
        params2.push('component/extension/content-render/content-xtpl');
        config1.params = params2;
        var id0 = getPropertyOrRunCommandUtil(engine, scopes, config1, "include", 0, 1, false, undefined);
        buffer += id0;
        buffer += '\r\n<div class="';
        var config4 = {};
        var params5 = [];
        params5.push('dropdown');
        config4.params = params5;
        var id3 = getPropertyOrRunCommandUtil(engine, scopes, config4, "getBaseCssClasses", 0, 2, true, undefined);
        buffer += id3;
        buffer += '">\r\n    <div class="';
        var config7 = {};
        var params8 = [];
        params8.push('dropdown-inner');
        config7.params = params8;
        var id6 = getPropertyOrRunCommandUtil(engine, scopes, config7, "getBaseCssClasses", 0, 3, true, undefined);
        buffer += id6;
        buffer += '">\r\n    </div>\r\n</div>';
        return buffer;
    }
});