/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('menubutton/menubutton-tpl',
'{{{include \'component/extension/content-render/content-tpl\'}}}\n<div class="{{getBaseCssClasses \'dropdown\'}}">\n    <div class="{{getBaseCssClasses \'dropdown-inner\'}}">\n    </div>\n</div>');
