/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('editor/render-tpl',
'<div class="{{prefixCls}}editor-tools"\n     id="ks-editor-tools-{{id}}">\n\n</div>\n\n<!--\nhttp://johanbrook.com/browsers/native-momentum-scrolling-ios-5/\nios 不能放在 iframe 上！\n-->\n\n<div class="{{prefixCls}}editor-textarea-wrap"\n\n{{#if mobile}}\nstyle="overflow:scroll;-webkit-overflow-scrolling:touch;"\n{{/if}}\n\nid="ks-editor-textarea-wrap-{{id}}"\n>\n\n<textarea\n        id="ks-editor-textarea-{{id}}"\n        class="{{prefixCls}}editor-textarea"\n\n{{#each textareaAttrs}}\n{{xkey}}="{{.}}"\n{{/each}}\n\n{{#if mode}}\nstyle="display:none"\n{{/if}}\n\n>{{data}}</textarea>\n\n</div>\n\n<div class="{{prefixCls}}editor-status"\n     id="ks-editor-status-{{id}}">\n\n</div>');
