/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('tree/node-tpl',
'<div id="ks-tree-node-row-{{id}}"\n     class="{{getBaseCssClasses \'row\'}}\n     {{#if selected}}\n        {{getBaseCssClasses \'selected\'}}\n     {{/if}}\n     ">\n    <div id="ks-tree-node-expand-icon-{{id}}"\n         class="{{getBaseCssClasses \'expand-icon\'}}">\n    </div>\n    {{#if checkable}}\n    <div id="ks-tree-node-checked-{{id}}"\n         class="{{getBaseCssClasses \'checked\'+checkState}}"></div>\n    {{/if}}\n    <div id="ks-tree-node-icon-{{id}}"\n         class="{{getBaseCssClasses \'icon\'}}">\n\n    </div>\n    {{{include \'component/extension/content-render/content-tpl\'}}}\n</div>\n<div id="ks-tree-node-children-{{id}}"\n     class="{{getBaseCssClasses \'children\'}}"\n{{^if expanded}}\nstyle="display:none"\n{{/if}}\n>\n</div>');
