/*Generated By KISSY Module Compiler*/
config({
'overlay': {requires: ['component/container','component/extension/align','node','component/extension/content-render','component/extension/shim-render']}
});
