/*Generated By KISSY Module Compiler*/
config('modules',{
'editor/plugin/link': {requires: ['editor','editor/plugin/bubble','editor/plugin/link/utils','editor/plugin/dialog-loader','editor/plugin/button']}
});
