/*Generated By KISSY Module Compiler*/
config({
'editor/plugin/link': {requires: ['editor/plugin/button','editor/plugin/bubble','editor','editor/plugin/link/utils','editor/plugin/dialog-loader']}
});
