KISSY.add(KISSY.noop,{
    requires:[
        './domain',
        './attr',
        './class',
        './clone',
        './create',
        './data','./input-selection',
        './insertion',
        './offset',
        './script',
        './scroll',
        './selector',
        './style',
        './traversal',
        './transform'
    ]
});