/*Generated By KISSY Module Compiler*/
config({
'editor/plugin/image': {requires: ['editor/plugin/button','editor','editor/plugin/bubble','editor/plugin/dialog-loader','editor/plugin/contextmenu']}
});
