/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/image': {requires: ['editor','editor/plugin/button','editor/plugin/bubble','editor/plugin/contextmenu','editor/plugin/dialog-loader']}
});
