module.exports=function(req,res,utils){
    res.send(utils.render('runner',{
        component:'combobox',
        externalLinks:[
            '/kissy/src/button/assets/picker.css',
            '/kissy/src/combobox/assets/picker.css',
            '/kissy/src/menu/assets/picker.css']
    }));
};