/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('scroll-view/plugin/scrollbar/scrollbar-tpl',
'<div id="ks-scrollbar-arrow-up-{{id}}"\n        class="{{getBaseCssClasses axis+"-arrow-up"}}">\n    <a href="javascript:void(\'up\')">up</a>\n</div>\n<div id="ks-scrollbar-arrow-down-{{id}}"\n        class="{{getBaseCssClasses axis+"-arrow-down"}}">\n    <a href="javascript:void(\'down\')">down</a>\n</div>\n<div id="ks-scrollbar-track-{{id}}"\n     class="{{getBaseCssClasses axis+"-track"}}">\n<div id="ks-scrollbar-drag-{{id}}"\n     class="{{getBaseCssClasses axis+"-drag"}}">\n<div class="{{getBaseCssClasses axis+"-drag-top"}}">\n</div>\n<div class="{{getBaseCssClasses axis+"-drag-center"}}">\n</div>\n<div class="{{getBaseCssClasses axis+"-drag-bottom"}}">\n</div>\n</div>\n</div>');
