/*
  Generated by kissy-xtemplate.*/
KISSY.add('scroll-view/plugin/scrollbar/scrollbar-xtpl', function () {
    return function (scopes, S, undefined) {
        var buffer = "",
            config = this.config,
            engine = this,
            utils = config.utils;
        var runBlockCommandUtil = utils["runBlockCommand"],
            getExpressionUtil = utils["getExpression"],
            getPropertyOrRunCommandUtil = utils["getPropertyOrRunCommand"];
        buffer += '<div id="ks-scrollbar-arrow-up-';
        var id0 = getPropertyOrRunCommandUtil(engine, scopes, {}, "id", 0, 1, undefined, false);
        buffer += getExpressionUtil(id0, true);
        buffer += '"\r\n        class="';
        var config2 = {};
        var params3 = [];
        var id4 = getPropertyOrRunCommandUtil(engine, scopes, {}, "axis", 0, 2, undefined, true);
        params3.push(id4 + ('-arrow-up'));
        config2.params = params3;
        var id1 = getPropertyOrRunCommandUtil(engine, scopes, config2, "getBaseCssClasses", 0, 2, true, undefined);
        buffer += id1;
        buffer += '">\r\n    <a href="javascript:void(\'up\')">up</a>\r\n</div>\r\n<div id="ks-scrollbar-arrow-down-';
        var id5 = getPropertyOrRunCommandUtil(engine, scopes, {}, "id", 0, 5, undefined, false);
        buffer += getExpressionUtil(id5, true);
        buffer += '"\r\n        class="';
        var config7 = {};
        var params8 = [];
        var id9 = getPropertyOrRunCommandUtil(engine, scopes, {}, "axis", 0, 6, undefined, true);
        params8.push(id9 + ('-arrow-down'));
        config7.params = params8;
        var id6 = getPropertyOrRunCommandUtil(engine, scopes, config7, "getBaseCssClasses", 0, 6, true, undefined);
        buffer += id6;
        buffer += '">\r\n    <a href="javascript:void(\'down\')">down</a>\r\n</div>\r\n<div id="ks-scrollbar-track-';
        var id10 = getPropertyOrRunCommandUtil(engine, scopes, {}, "id", 0, 9, undefined, false);
        buffer += getExpressionUtil(id10, true);
        buffer += '"\r\n     class="';
        var config12 = {};
        var params13 = [];
        var id14 = getPropertyOrRunCommandUtil(engine, scopes, {}, "axis", 0, 10, undefined, true);
        params13.push(id14 + ('-track'));
        config12.params = params13;
        var id11 = getPropertyOrRunCommandUtil(engine, scopes, config12, "getBaseCssClasses", 0, 10, true, undefined);
        buffer += id11;
        buffer += '">\r\n<div id="ks-scrollbar-drag-';
        var id15 = getPropertyOrRunCommandUtil(engine, scopes, {}, "id", 0, 11, undefined, false);
        buffer += getExpressionUtil(id15, true);
        buffer += '"\r\n     class="';
        var config17 = {};
        var params18 = [];
        var id19 = getPropertyOrRunCommandUtil(engine, scopes, {}, "axis", 0, 12, undefined, true);
        params18.push(id19 + ('-drag'));
        config17.params = params18;
        var id16 = getPropertyOrRunCommandUtil(engine, scopes, config17, "getBaseCssClasses", 0, 12, true, undefined);
        buffer += id16;
        buffer += '">\r\n<div class="';
        var config21 = {};
        var params22 = [];
        var id23 = getPropertyOrRunCommandUtil(engine, scopes, {}, "axis", 0, 13, undefined, true);
        params22.push(id23 + ('-drag-top'));
        config21.params = params22;
        var id20 = getPropertyOrRunCommandUtil(engine, scopes, config21, "getBaseCssClasses", 0, 13, true, undefined);
        buffer += id20;
        buffer += '">\r\n</div>\r\n<div class="';
        var config25 = {};
        var params26 = [];
        var id27 = getPropertyOrRunCommandUtil(engine, scopes, {}, "axis", 0, 15, undefined, true);
        params26.push(id27 + ('-drag-center'));
        config25.params = params26;
        var id24 = getPropertyOrRunCommandUtil(engine, scopes, config25, "getBaseCssClasses", 0, 15, true, undefined);
        buffer += id24;
        buffer += '">\r\n</div>\r\n<div class="';
        var config29 = {};
        var params30 = [];
        var id31 = getPropertyOrRunCommandUtil(engine, scopes, {}, "axis", 0, 17, undefined, true);
        params30.push(id31 + ('-drag-bottom'));
        config29.params = params30;
        var id28 = getPropertyOrRunCommandUtil(engine, scopes, config29, "getBaseCssClasses", 0, 17, true, undefined);
        buffer += id28;
        buffer += '">\r\n</div>\r\n</div>\r\n</div>';
        return buffer;
    }
});