/*
  Generated by kissy-xtemplate.*/
KISSY.add('menu/submenu-xtpl', function () {
    return function (scopes, S, undefined) {
        var buffer = "",
            config = this.config,
            engine = this,
            utils = config.utils;
        var runBlockCommandUtil = utils["runBlockCommand"],
            getExpressionUtil = utils["getExpression"],
            getPropertyOrRunCommandUtil = utils["getPropertyOrRunCommand"];
        buffer += '';
        var config1 = {};
        var params2 = [];
        params2.push('component/extension/content-render/content-xtpl');
        config1.params = params2;
        var id0 = getPropertyOrRunCommandUtil(engine, scopes, config1, "include", 0, 1, false, undefined);
        buffer += id0;
        buffer += '\r\n<span class="';
        var id3 = getPropertyOrRunCommandUtil(engine, scopes, {}, "prefixCls", 0, 2, undefined, false);
        buffer += getExpressionUtil(id3, true);
        buffer += 'submenu-arrow">►</span>';
        return buffer;
    }
});