/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('menu/submenu-tpl',
'<span id="ks-menuitem-content-{{id}}" class="{{getBaseCssClasses "content"}}"> {{{content}}} </span> <span class="{{getBaseCssClasses "arrow"}}">►</span>');
