/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/xiami-music': {requires: ['editor','editor/plugin/flash-common/base-class','editor/plugin/flash-common/utils','editor/plugin/fake-objects']}
});
