/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('overlay/close-tpl',
'<a href="javascript:void(\'close\')"\n   id="ks-overlay-close-{{id}}"\n   class="{{getBaseCssClasses "close"}}"\n   role=\'button\'>\n    <span class="{{getBaseCssClasses "close-x"}}">close</span>\n</a>');
