/*
  Generated by kissy-xtemplate.*/
KISSY.add('overlay/close-xtpl', function () {
    return function (scopes, S, undefined) {
        var buffer = "",
            config = this.config,
            engine = this,
            utils = config.utils;
        var runBlockCommandUtil = utils["runBlockCommand"],
            getExpressionUtil = utils["getExpression"],
            getPropertyOrRunCommandUtil = utils["getPropertyOrRunCommand"];
        buffer += '<a href="javascript:void(\'close\')"\r\n   id="ks-overlay-close-';
        var id0 = getPropertyOrRunCommandUtil(engine, scopes, {}, "id", 0, 2, undefined, false);
        buffer += getExpressionUtil(id0, true);
        buffer += '"\r\n   class="';
        var config2 = {};
        var params3 = [];
        params3.push('close');
        config2.params = params3;
        var id1 = getPropertyOrRunCommandUtil(engine, scopes, config2, "getBaseCssClasses", 0, 3, true, undefined);
        buffer += id1;
        buffer += '"\r\n   role=\'button\'>\r\n    <span class="';
        var config5 = {};
        var params6 = [];
        params6.push('close-x');
        config5.params = params6;
        var id4 = getPropertyOrRunCommandUtil(engine, scopes, config5, "getBaseCssClasses", 0, 5, true, undefined);
        buffer += id4;
        buffer += '">close</span>\r\n</a>\r\n';
        return buffer;
    }
});