/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('overlay/close-tpl',
'<a href="javascript:void(\'close\')" id="ks-overlay-close-{{id}}" class="{{getBaseCssClasses "close"}}" role=\'button\'> <span class="{{getBaseCssClasses "close-x"}}">close</span> </a>');
