/*
  Generated by kissy-xtemplate.*/
KISSY.add('overlay/dialog-xtpl', function () {
    return function (scopes, S, undefined) {
        var buffer = "",
            config = this.config,
            engine = this,
            utils = config.utils;
        var runBlockCommandUtil = utils["runBlockCommand"],
            getExpressionUtil = utils["getExpression"],
            getPropertyOrRunCommandUtil = utils["getPropertyOrRunCommand"];
        buffer += '';
        var config1 = {};
        var params2 = [];
        params2.push('overlay/close-xtpl');
        config1.params = params2;
        var id0 = getPropertyOrRunCommandUtil(engine, scopes, config1, "include", 0, 1, false, undefined);
        buffer += id0;
        buffer += '\r\n<div id="ks-content-';
        var id3 = getPropertyOrRunCommandUtil(engine, scopes, {}, "id", 0, 2, undefined, false);
        buffer += getExpressionUtil(id3, true);
        buffer += '"\r\n     class="';
        var config5 = {};
        var params6 = [];
        params6.push('content');
        config5.params = params6;
        var id4 = getPropertyOrRunCommandUtil(engine, scopes, config5, "getBaseCssClasses", 0, 3, true, undefined);
        buffer += id4;
        buffer += '">\r\n    <div class="';
        var config8 = {};
        var params9 = [];
        params9.push('header');
        config8.params = params9;
        var id7 = getPropertyOrRunCommandUtil(engine, scopes, config8, "getBaseCssClasses", 0, 4, true, undefined);
        buffer += id7;
        buffer += '"\r\n         style="\r\n';
        var config10 = {};
        var params11 = [];
        var id12 = getPropertyOrRunCommandUtil(engine, scopes, {}, "headerStyle", 0, 6, undefined, true);
        params11.push(id12);
        config10.params = params11;
        config10.fn = function (scopes) {
            var buffer = "";
            buffer += ' \r\n ';
            var id13 = getPropertyOrRunCommandUtil(engine, scopes, {}, "xindex", 0, 7, undefined, false);
            buffer += getExpressionUtil(id13, true);
            buffer += ':';
            var id14 = getPropertyOrRunCommandUtil(engine, scopes, {}, ".", 0, 7, undefined, false);
            buffer += getExpressionUtil(id14, true);
            buffer += ';\r\n';
            return buffer;
        };
        buffer += runBlockCommandUtil(engine, scopes, config10, "each", 6);
        buffer += '\r\n"\r\n         id="ks-stdmod-header-';
        var id15 = getPropertyOrRunCommandUtil(engine, scopes, {}, "id", 0, 10, undefined, false);
        buffer += getExpressionUtil(id15, true);
        buffer += '">';
        var id16 = getPropertyOrRunCommandUtil(engine, scopes, {}, "headerContent", 0, 10, undefined, false);
        buffer += getExpressionUtil(id16, false);
        buffer += '\r\n    </div>\r\n\r\n    <div class="';
        var config18 = {};
        var params19 = [];
        params19.push('body');
        config18.params = params19;
        var id17 = getPropertyOrRunCommandUtil(engine, scopes, config18, "getBaseCssClasses", 0, 13, true, undefined);
        buffer += id17;
        buffer += '"\r\n         style="\r\n';
        var config20 = {};
        var params21 = [];
        var id22 = getPropertyOrRunCommandUtil(engine, scopes, {}, "bodyStyle", 0, 15, undefined, true);
        params21.push(id22);
        config20.params = params21;
        config20.fn = function (scopes) {
            var buffer = "";
            buffer += ' \r\n ';
            var id23 = getPropertyOrRunCommandUtil(engine, scopes, {}, "xindex", 0, 16, undefined, false);
            buffer += getExpressionUtil(id23, true);
            buffer += ':';
            var id24 = getPropertyOrRunCommandUtil(engine, scopes, {}, ".", 0, 16, undefined, false);
            buffer += getExpressionUtil(id24, true);
            buffer += ';\r\n';
            return buffer;
        };
        buffer += runBlockCommandUtil(engine, scopes, config20, "each", 15);
        buffer += '\r\n"\r\n         id="ks-stdmod-body-';
        var id25 = getPropertyOrRunCommandUtil(engine, scopes, {}, "id", 0, 19, undefined, false);
        buffer += getExpressionUtil(id25, true);
        buffer += '">';
        var id26 = getPropertyOrRunCommandUtil(engine, scopes, {}, "bodyContent", 0, 19, undefined, false);
        buffer += getExpressionUtil(id26, false);
        buffer += '\r\n    </div>\r\n\r\n    <div class="';
        var config28 = {};
        var params29 = [];
        params29.push('footer');
        config28.params = params29;
        var id27 = getPropertyOrRunCommandUtil(engine, scopes, config28, "getBaseCssClasses", 0, 22, true, undefined);
        buffer += id27;
        buffer += '"\r\n         style="\r\n';
        var config30 = {};
        var params31 = [];
        var id32 = getPropertyOrRunCommandUtil(engine, scopes, {}, "footerStyle", 0, 24, undefined, true);
        params31.push(id32);
        config30.params = params31;
        config30.fn = function (scopes) {
            var buffer = "";
            buffer += ' \r\n ';
            var id33 = getPropertyOrRunCommandUtil(engine, scopes, {}, "xindex", 0, 25, undefined, false);
            buffer += getExpressionUtil(id33, true);
            buffer += ':';
            var id34 = getPropertyOrRunCommandUtil(engine, scopes, {}, ".", 0, 25, undefined, false);
            buffer += getExpressionUtil(id34, true);
            buffer += ';\r\n';
            return buffer;
        };
        buffer += runBlockCommandUtil(engine, scopes, config30, "each", 24);
        buffer += '\r\n"\r\n         id="ks-stdmod-footer-';
        var id35 = getPropertyOrRunCommandUtil(engine, scopes, {}, "id", 0, 28, undefined, false);
        buffer += getExpressionUtil(id35, true);
        buffer += '">';
        var id36 = getPropertyOrRunCommandUtil(engine, scopes, {}, "footerContent", 0, 28, undefined, false);
        buffer += getExpressionUtil(id36, false);
        buffer += '\r\n    </div>\r\n</div>\r\n<div tabindex="0"></div>';
        return buffer;
    }
});