/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('overlay/dialog-tpl',
'<div class="{{getBaseCssClasses \'header\'}}"\n     style="\n{{#each headerStyle}} \n {{xkey}}:{{.}};  \n{{/each}}\n"\n     id="ks-stdmod-header-{{id}}">{{{headerContent}}}</div>\n\n<div class="{{getBaseCssClasses \'body\'}}"\n     style="\n{{#each bodyStyle}} \n {{xkey}}:{{.}};  \n{{/each}}\n"\n     id="ks-stdmod-body-{{id}}">{{{bodyContent}}}</div>\n\n<div class="{{getBaseCssClasses \'footer\'}}"\n     style="\n{{#each footerStyle}} \n {{xkey}}:{{.}};  \n{{/each}}\n"\n     id="ks-stdmod-footer-{{id}}">{{{footerContent}}}</div>');
