/*Generated By KISSY Module Compiler*/
config({
'menu': {requires: ['node','component/container','component/extension/delegate-children','component/controller','component/extension/content-render','component/extension/align','component/extension/shim-render']}
});
