
(function(config,Features,UA){
config({
    anim: {
        alias: ['anim/facade']
    }
});/*Generated By KISSY Module Compiler*/
config('modules',{
'anim/base': {requires: ['dom','event/custom']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'anim/facade': {requires: ['dom','anim/base','anim/timer',KISSY.Features.isTransitionSupported() ? "anim/transition" : ""]}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'anim/timer': {requires: ['dom','event','anim/base']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'anim/transition': {requires: ['dom','event','anim/base']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'base': {requires: ['event/custom']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'button': {requires: ['event','component/base']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'calendar': {requires: ['node','event']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'color': {requires: ['base']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'combobox': {requires: ['node','component/base','menu','dom','io']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'component/base': {requires: ['rich-base','node','event','xtemplate']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'component/extension': {requires: ['dom','node','event','component/base']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'component/plugin/drag': {requires: ['rich-base','dd/base']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'component/plugin/resize': {requires: ['resizable']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'dd/base': {requires: ['dom','event','node','base','rich-base']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'dd/droppable': {requires: ['dd/base','node','rich-base','dom']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'dd/plugin/constrain': {requires: ['base','node']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'dd/plugin/proxy': {requires: ['node','base','dd/base']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'dd/plugin/scroll': {requires: ['dd/base','base','node','dom']}
});
config({
    "dom/basic": {
        "alias": [
            'dom/base',
            Features.isIELessThan(9) ? 'dom/ie' : '',
            Features.isClassListSupported() ? '' : 'dom/class-list'
        ]
    },
    "dom": {
        "alias": [
            'dom/basic',
            !Features.isQuerySelectorSupported() ? 'dom/selector' : ''
        ]
    }
});/*Generated By KISSY Module Compiler*/
config('modules',{
'dom/class-list': {requires: ['dom/base']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'dom/ie': {requires: ['dom/base']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'dom/selector': {requires: ['dom/basic']}
});
config({
    'editor': {alias: ['editor/core']}
});/*Generated By KISSY Module Compiler*/
config('modules',{
'editor/core': {requires: ['htmlparser','component/base','core']}
});
config({
    "event": {
        "alias": ["event/base", "event/dom", "event/custom"]
    }
});/*Generated By KISSY Module Compiler*/
config('modules',{
'event/custom': {requires: ['event/base']}
});
config({
    "event/dom": {
        "alias": [
            "event/dom/base",
            Features.isTouchSupported() ? 'event/dom/touch' : '',
            Features.isDeviceMotionSupported() ? 'event/dom/shake' : '',
            Features.isHashChangeSupported() ? '' : 'event/dom/hashchange',
            Features.isIELessThan(9) ? 'event/dom/ie' : '',
            UA.ie ? '' : 'event/dom/focusin'
        ]
    }
});/*Generated By KISSY Module Compiler*/
config('modules',{
'event/dom/base': {requires: ['event/base','dom']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'event/dom/focusin': {requires: ['event/dom/base']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'event/dom/hashchange': {requires: ['event/dom/base','dom']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'event/dom/ie': {requires: ['event/dom/base','dom']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'event/dom/shake': {requires: ['event/dom/base']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'event/dom/touch': {requires: ['event/dom/base','dom']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'imagezoom': {requires: ['node','overlay']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'io': {requires: ['dom','json','event']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'kison': {requires: ['base']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'menu': {requires: ['event','component/base','component/extension','node']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'menubutton': {requires: ['node','button','component/extension','menu']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'mvc': {requires: ['base','event','node','io','json']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'node': {requires: ['dom','event/dom','anim']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'overlay': {requires: ['component/base','component/extension','event','xtemplate','node']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'resizable': {requires: ['node','rich-base','dd/base']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'rich-base': {requires: ['base']}
});
config({
    "scrollview": {
        "alias": [Features.isTouchSupported() ? 'scrollview/drag' : 'scrollview/base']
    }
});/*Generated By KISSY Module Compiler*/
config('modules',{
'scrollview/base': {requires: ['dom','component/base','component/extension','event']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'scrollview/drag': {requires: ['scrollview/base','dd/base','event']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'scrollview/plugin/scrollbar': {requires: ['base','event','dd/base','component/base']}
});
/**
 * @ignore
 * Default KISSY Gallery and core alias.
 * @author yiminghe@gmail.com
 */
(function (S) {
    var parentUri = S.Config.baseUri.resolve('../').toString();
    S.config({
        packages: {
            gallery: {
                base: parentUri
            },
            mobile: {
                base: parentUri
            }
        },
        modules: {
            core: {
                alias: ['dom', 'event', 'io', 'anim', 'base', 'node', 'json', 'ua','cookie']
            }
        }
    });
})(KISSY);

(function(config,Features,UA){
config({
    anim: {
        alias: ['anim/facade']
    }
});/*Generated by KISSY Module Compiler*/
config({
'anim/base': {requires: ['dom','event/custom']}
});
/*Generated by KISSY Module Compiler*/
config({
'anim/facade': {requires: ['dom','anim/base','anim/timer',KISSY.Features.isTransitionSupported() ? "anim/transition" : ""]}
});
/*Generated by KISSY Module Compiler*/
config({
'anim/timer': {requires: ['dom','event','anim/base']}
});
/*Generated by KISSY Module Compiler*/
config({
'anim/transition': {requires: ['dom','event','anim/base']}
});
/*Generated by KISSY Module Compiler*/
config({
'base': {requires: ['event/custom']}
});
/*Generated by KISSY Module Compiler*/
config({
'button': {requires: ['component/base','event']}
});
/*Generated by KISSY Module Compiler*/
config({
'calendar': {requires: ['node','event']}
});
/*Generated by KISSY Module Compiler*/
config({
'color': {requires: ['base']}
});
/*Generated by KISSY Module Compiler*/
config({
'combobox': {requires: ['dom','component/base','node','menu','io']}
});
/*Generated by KISSY Module Compiler*/
config({
'component/base': {requires: ['rich-base','node','xtemplate','event']}
});
/*Generated by KISSY Module Compiler*/
config({
'component/extension': {requires: ['event','component/base','dom','node']}
});
/*Generated by KISSY Module Compiler*/
config({
'component/plugin/drag': {requires: ['rich-base','dd/base']}
});
/*Generated by KISSY Module Compiler*/
config({
'component/plugin/resize': {requires: ['resizable']}
});
config({
    'dd': {alias: ['dd/base', 'dd/droppable']}
});
/*Generated by KISSY Module Compiler*/
config({
'dd/base': {requires: ['dom','node','event','rich-base','base']}
});
/*Generated by KISSY Module Compiler*/
config({
'dd/droppable': {requires: ['dd/base','dom','node','rich-base']}
});
/*Generated by KISSY Module Compiler*/
config({
'dd/plugin/constrain': {requires: ['base','node']}
});
/*Generated by KISSY Module Compiler*/
config({
'dd/plugin/proxy': {requires: ['node','base','dd/base']}
});
/*Generated by KISSY Module Compiler*/
config({
'dd/plugin/scroll': {requires: ['dd/base','base','node','dom']}
});
config({
    "dom/basic": {
        "alias": [
            'dom/base',
            Features.isIELessThan(9) ? 'dom/ie' : '',
            Features.isClassListSupported() ? '' : 'dom/class-list'
        ]
    },
    "dom": {
        "alias": [
            'dom/basic',
            !Features.isQuerySelectorSupported() ? 'dom/selector' : ''
        ]
    }
});/*Generated by KISSY Module Compiler*/
config({
'dom/class-list': {requires: ['dom/base']}
});
/*Generated by KISSY Module Compiler*/
config({
'dom/ie': {requires: ['dom/base']}
});
/*Generated by KISSY Module Compiler*/
config({
'dom/selector': {requires: ['dom/basic']}
});
config({
    'editor': {alias: ['editor/core']}
});
/*Generated by KISSY Module Compiler*/
config({
'editor/core': {requires: ['htmlparser','component/base','core']}
});
config({
    "event": {
        "alias": ["event/base", "event/dom", "event/custom"]
    }
});/*Generated by KISSY Module Compiler*/
config({
'event/custom': {requires: ['event/base']}
});
config({
    "event/dom": {
        "alias": [
            "event/dom/base",
            Features.isTouchSupported() ? 'event/dom/touch' : '',
            Features.isDeviceMotionSupported() ? 'event/dom/shake' : '',
            Features.isHashChangeSupported() ? '' : 'event/dom/hashchange',
            Features.isIELessThan(9) ? 'event/dom/ie' : '',
            UA.ie ? '' : 'event/dom/focusin'
        ]
    }
});/*Generated by KISSY Module Compiler*/
config({
'event/dom/base': {requires: ['dom','event/base']}
});
/*Generated by KISSY Module Compiler*/
config({
'event/dom/focusin': {requires: ['event/dom/base']}
});
/*Generated by KISSY Module Compiler*/
config({
'event/dom/hashchange': {requires: ['event/dom/base','dom']}
});
/*Generated by KISSY Module Compiler*/
config({
'event/dom/ie': {requires: ['event/dom/base','dom']}
});
/*Generated by KISSY Module Compiler*/
config({
'event/dom/shake': {requires: ['event/dom/base']}
});
/*Generated by KISSY Module Compiler*/
config({
'event/dom/touch': {requires: ['event/dom/base','dom']}
});
/*Generated by KISSY Module Compiler*/
config({
'imagezoom': {requires: ['node','overlay']}
});
config({
'ajax': {alias: ['io']}
});
/*Generated by KISSY Module Compiler*/
config({
'io': {requires: ['dom','event','json']}
});
/*Generated by KISSY Module Compiler*/
config({
'kison': {requires: ['base']}
});
/*Generated by KISSY Module Compiler*/
config({
'menu': {requires: ['component/extension','node','component/base','event']}
});
/*Generated by KISSY Module Compiler*/
config({
'menubutton': {requires: ['node','menu','button','component/extension']}
});
/*Generated by KISSY Module Compiler*/
config({
'mvc': {requires: ['event','base','io','json','node']}
});
/*Generated by KISSY Module Compiler*/
config({
'node': {requires: ['dom','event/dom','anim']}
});
/*Generated by KISSY Module Compiler*/
config({
'overlay': {requires: ['component/base','component/extension','node','xtemplate','event']}
});
/*Generated by KISSY Module Compiler*/
config({
'resizable': {requires: ['node','rich-base','dd/base']}
});
/*Generated by KISSY Module Compiler*/
config({
'rich-base': {requires: ['base']}
});
config({
    "scrollview": {
        "alias": [Features.isTouchSupported() ? 'scrollview/drag' : 'scrollview/base']
    }
});/*Generated by KISSY Module Compiler*/
config({
'scrollview/base': {requires: ['component/base','component/extension','dom','event']}
});
/*Generated by KISSY Module Compiler*/
config({
'scrollview/drag': {requires: ['scrollview/base','dd/base','event']}
});
/*Generated by KISSY Module Compiler*/
config({
'scrollview/plugin/scrollbar': {requires: ['component/base','event','dd/base','base']}
});
/*Generated by KISSY Module Compiler*/
config({
'separator': {requires: ['component/base']}
});
/*Generated by KISSY Module Compiler*/
config({
'split-button': {requires: ['component/base','button','menubutton']}
});
/*Generated by KISSY Module Compiler*/
config({
'stylesheet': {requires: ['dom']}
});
/*Generated by KISSY Module Compiler*/
config({
'swf': {requires: ['dom','json','base']}
});
/*Generated by KISSY Module Compiler*/
config({
'tabs': {requires: ['button','toolbar','component/base','component/extension']}
});
/*Generated by KISSY Module Compiler*/
config({
'toolbar': {requires: ['component/base','component/extension','node']}
});
/*Generated by KISSY Module Compiler*/
config({
'tree': {requires: ['node','component/base','component/extension','event']}
});
/*Generated by KISSY Module Compiler*/
config({
'waterfall': {requires: ['node','base']}
});
config({
    xtemplate: {
        alias: ['xtemplate/facade']
    }
});/*Generated by KISSY Module Compiler*/
config({
'xtemplate/compiler': {requires: ['xtemplate/runtime']}
});
/*Generated by KISSY Module Compiler*/
config({
'xtemplate/facade': {requires: ['xtemplate/runtime','xtemplate/compiler']}
});

                })(function(c){
                KISSY.config('modules', c);
                },KISSY.Features,KISSY.UA);
            /*Generated By KISSY Module Compiler*/
config('modules',{
'separator': {requires: ['component/base']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'split-button': {requires: ['component/base','button','menubutton']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'stylesheet': {requires: ['dom']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'swf': {requires: ['dom','json','base']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'tabs': {requires: ['component/base','toolbar','component/extension','button']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'toolbar': {requires: ['component/base','component/extension','node']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'tree': {requires: ['component/base','node','component/extension','event']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'waterfall': {requires: ['node','base']}
});
config({
    xtemplate: {
        alias: ['xtemplate/facade']
    }
});/*Generated By KISSY Module Compiler*/
config('modules',{
'xtemplate/compiler': {requires: ['xtemplate/runtime']}
});
/*Generated By KISSY Module Compiler*/
config('modules',{
'xtemplate/facade': {requires: ['xtemplate/runtime','xtemplate/compiler']}
});

                })(function(c){
                KISSY.config('modules', c);
                },KISSY.Features,KISSY.UA);
            