/*Generated by KISSY Module Compiler*/
config({
'editor/plugin/multiple-upload/dialog': {requires: ['editor','component/plugin/drag','editor/plugin/progressbar','editor/plugin/dialog','editor/plugin/flash-bridge','editor/plugin/local-storage','swf']}
});
