/*Generated by KISSY Module Compiler*/
KISSY.config('processedModules', {
'overlay': {requires: ['dom','event','component']},
'event': {requires: ['dom','dom/ie','ua']},
'switch': {requires: ['dom','uibase/position']},
'dom/ie': {requires: ['dom/base']},
'page/run': {requires: ['switch','overlay']}
});
