/*Generated By KISSY Module Compiler*/
config({
'editor/plugin/flash': {requires: ['editor','editor/plugin/flash-common/base-class','editor/plugin/flash-common/utils','editor/plugin/fake-objects','editor/plugin/button']}
});
