/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('menu/filtermenu-tpl',function(){
 return '<div id="ks-menu-filter{{id}}"\n     class="{{prefixCls}}menu-filter">\n    <div id="ks-menu-filter-label{{id}}"\n         class="{{prefixCls}}menu-filter-label">\n        {{label}}\n    </div>\n    <input id="ks-menu-filter-input{{id}}"\n           class="{{prefixCls}}menu-filter-label"\n           autocomplete="off"/>\n</div>\n<div id="ks-menu-content{{id}}"\n     class="{{prefixCls}}menu-content">\n</div>';
});
