/*
  Generated by kissy-tpl2mod.
*/
KISSY.add('menu/submenu-tpl',function(){
 return '<span id="ks-menuitem-content{{id}}"\nclass="{{prefixCls}}menuitem-content">\n    {{{content}}}\n</span>\n<span class="{{prefixCls}}submenu-arrow">►</span>';
});
